# Default initial positions for Robot's ros2_control fake system

initial_positions:
  Idol Joint: -0.5934
  Joint1: 0
  Joint2: 0
  Joint3: 0
  Joint4: 0
  Joint5: 0
  Joint6: 0
  Servo Joint: -0.6458